from __future__ import annotations

# v0.15 PG01-PG40: compact executable registry used by the conformance surface.
PRINCIPAL_SCOPE_FAILURES = {
    "PG01": ("runtime-global fact treated as known by every principal", "principal-scoped information partition"),
    "PG02": ("A observed a fact but B conditions on it without transfer", "principal observation history scope"),
    "PG03": ("access profiles differ but shared partition reused", "access-profile dependency"),
    "PG04": ("message sent treated as delivered", "delivery/reveal evidence"),
    "PG05": ("late delivery conditions earlier decision", "observation frontier and deadline"),
    "PG06": ("A capsule handed unchanged to B", "recipient-principal binding"),
    "PG07": ("fetch handle hydrates A-only evidence for B", "principal-scoped hydration"),
    "PG08": ("access profile changes after capsule compilation", "access revision invalidation"),
    "PG09": ("role label substituted for principal identity", "canonical principal ref"),
    "PG10": ("same model/session labels collapse principals", "host-attested distinction"),
    "PG11": ("worker restart creates a new principal incorrectly", "principal continuity"),
    "PG12": ("worker replacement inherits principal implicitly", "explicit principal rebinding"),
    "PG13": ("partition reused across principals without equivalence", "prove equivalence or recompile"),
    "PG14": ("DecisionEpoch uses global information signature", "principal-relative non-anticipativity"),
    "PG15": ("recall proof includes inaccessible evidence", "principal-scoped recall"),
    "PG16": ("ambiguous identity defaults to most-authorized", "typed inconclusive identity"),
    "PG17": ("authorization for A presented by B", "acting_principal_ref"),
    "PG18": ("grant principal mismatch ignored", "grant/principal compatibility"),
    "PG19": ("copied authorization confers authority", "principal-bound authorization"),
    "PG20": ("dispatch fence omits principal", "dispatch identity attestation"),
    "PG21": ("endpoint identity mistaken for acting principal", "separate endpoint/principal identity"),
    "PG22": ("principal changes after authorization", "dispatch-time principal recheck"),
    "PG23": ("revoked A auth dispatched by B worker", "presented/acting match"),
    "PG24": ("coauthorization from incompatible context", "principal-compatible composition"),
    "PG25": ("executor-sensitive route omits executor", "execution-principal requirement"),
    "PG26": ("A information composed with B authority implicitly", "separate information/execution binding"),
    "PG27": ("receipt lacks executing principal", "receipt principal attribution"),
    "PG28": ("opaque dispatcher assumed intended principal", "identity assurance ceiling"),
    "PG29": ("delegation forwards bearer authorization", "canonical delegate grant"),
    "PG30": ("handoff reuses old principal capsule", "handoff principal revalidation"),
    "PG31": ("agent leave deletes obligation", "condition-centric obligation identity"),
    "PG32": ("unique departed-agent route stays feasible", "regime/capability invalidation"),
    "PG33": ("new principal inherits old authority", "normal grant validation"),
    "PG34": ("exclusive resource double reservation", "SharedCommitment feasibility"),
    "PG35": ("same model lineage counted independent", "evidence lineage dependence"),
    "PG36": ("access changes but policy stays sealed", "principal-scope freshness edge"),
    "PG37": ("principal/environment mismatch ignored", "environment plus principal binding"),
    "PG38": ("stale identity after host migration", "versioned identity provenance"),
    "PG39": ("multi-agent interpreted as multi-writer", "single serialized correctness writer"),
    "PG40": ("v0.15 advertised as generic orchestration", "scope/non-goal boundary"),
}
